version: '3.4'

services:
  web:
    build:
      context: .
      target: base
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  css:
    build:
      context: .
      target: base
    command: bin/rails tailwindcss:watch[debug]
    tty: true
    volumes:
      - .:/app
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
