version: '3.4'

services:
  ci:
    image: app:ci
    profiles:
      - ci
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:6
